version: "3.9"
services:
  nextjs:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: astra_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
    working_dir: /app
    env_file:
      - .env
    command: >
      bash -c "
      npm install
      npm run dev
      "
    networks:
      - astra-net

  service_tier:
    build:
      context: service_tier
    container_name: service_tier
    depends_on:
      - db
    env_file:
      - .env
    #command: celery -A celery_app worker --loglevel=info
    command: tail -f /dev/null
    volumes:
      - ./service_tier:/app
    networks:
      - astra-net

networks:
  astra-net: