AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        AWS_REGION: us-east-1
        BUCKET_NAME: !Ref ServiceBucket

Resources:
  ServiceTierFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          STAGE: local
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ServiceBucket
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ServiceTierQueue.Arn
            BatchSize: 1
    Metadata:
      DockerContext: ./src/service_tier
      Dockerfile: Dockerfile

  CronFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          STAGE: local
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
    Metadata:
      DockerContext: ./src/cron
      Dockerfile: Dockerfile

  ServiceTierQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  ServiceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-bucket