version: "3.9"
services:
  service_tier:
    build:
      context: .
    container_name: service_tier
    # depends_on:
    #   - db
    env_file:
      - ../.env
    command: tail -f /dev/null
    volumes:
      - .:/app
    networks:
      - astra-net

networks:
  astra-net: