version: '3.8'

services:
  podcast-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_ACCESS_URL=${DB_ACCESS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 